Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/Pythone1.py", line 9, in <module>
    print(ember + x)
TypeError: must be str, not int
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Lajoska12
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Lajoska 12
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Lajoska 12
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
42 12
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
42*12=
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
42*12= 504
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/Pythone1.py", line 14, in <module>
    print(str (ember) + "*" + str(x) + "=", + str (ember*x))
TypeError: bad operand type for unary +: 'str'
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
42*12=504
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
42*12=504
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/Pythone1.py", line 17, in <module>
    print(X)
NameError: name 'X' is not defined
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
42*12=504
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/Pythone1.py", line 17, in <module>
    print(X)
NameError: name 'X' is not defined
>>> 
============== RESTART: H:/Git hub feladatok/Pyton/Pythone1.py ==============
12
Lajoska
Jaloska 12
42*12=504
13
>>> 
